<div class="col-xs-12 col-sm-12 col-md-8 col-lg-6 col-xl-8">
                <div class="card" style="background: #BAE6DC; border: 0;">
                    <!--div class="card-block"-->
                        <!-- #region Jssor Slider Begin -->
                        <!-- Generated by Jssor Slider Maker Online. -->
                        <!-- This demo works with jquery library -->

                        <script type="text/javascript" src="js/jquery-1.9.1.min.js"></script>
                        <script type="text/javascript" src="js/jssor.slider.mini.js"></script>
                        <!-- use jssor.slider.debug.js instead for debug -->
                            <script>
                                jQuery(document).ready(function ($) {
                                    
                                    var jssor_1_options = {
                                      $AutoPlay: true,
                                      $SlideWidth: 600,
                                      $Cols: 2,
                                      $Align: 100,
                                      $ArrowNavigatorOptions: {
                                        $Class: $JssorArrowNavigator$
                                      },
                                      $BulletNavigatorOptions: {
                                        $Class: $JssorBulletNavigator$
                                      }
                                    };
                                    
                                    var jssor_1_slider = new $JssorSlider$("jssor_1", jssor_1_options);
                                    
                                    //responsive code begin
                                    //you can remove responsive code if you don't want the slider scales while window resizing
                                    function ScaleSlider() {
                                        var refSize = jssor_1_slider.$Elmt.parentNode.clientWidth;
                                        if (refSize) {
                                            refSize = Math.min(refSize, 800);
                                            jssor_1_slider.$ScaleWidth(refSize);
                                        }
                                        else {
                                            window.setTimeout(ScaleSlider, 30);
                                        }
                                    }
                                    ScaleSlider();
                                    $(window).bind("load", ScaleSlider);
                                    $(window).bind("resize", ScaleSlider);
                                    $(window).bind("orientationchange", ScaleSlider);
                                    //responsive code end
                                });
                            </script>

                            <?php include 'includes/slide.php'; ?>
                </div>
            </div>